language: java
jdk: oraclejdk10 #Oracle JDK has JavaFX bundled in version 10 and prior. JavaFX removed from version 11 and above
install: true
sudo: true
group: stable
dist: precise
os: linux
branches:
  only:
  - master
cache:
  directories:
  - $HOME/.gradle
before_install:
- chmod +x gradlew